name: Deploy to GitHub Pages

on:
  push:
    branches: [master]  # or main, depending on your default branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List dist contents
        run: ls -R dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}  # Use your PAT here
          folder: dist  # This should deploy only the dist folder
          branch: gh-pages
          clean: true
          single-commit: true
